export const RESPONSE = {
	SUCCESS: 'success',
	EXISTING_USERNAME: 'Username already existed',
	INVALID_EMAIL: 'Invalid email address',
	EXISTING_EMAIL: 'Email already exists',
	INVALID_CREDENTIALS: 'Invalid username or password',
	NO_USER_FOUND: 'No user found',
	INVALID_TOKEN: 'Invalid token',
	NEW_GROUP: 'Group created successfully',
	ADD_NEW_MEMBERS: 'New members added successfully',
	LOGIN_SUCCESS: 'Login Successfull',
	SIGNUP_SUCCESS: 'User created succesfully',
	REQUIRED_TOKEN: 'Token required',
	EXPIRED_TOKEN: 'Expired Token',
	FAILED_TOKEN_VALIDATION: 'Failed to authenticate user',
	NEW_FRIEND_REQUEST: 'Friend request sent',
	EXISTED_FRIEND_REQUEST: 'Friend request is already sent to this user',
	ACCEPTED_FRIEND_REQUEST: 'This user is already your friend',
	EXISTED_PENDING_REQUEST: 'You have already pending request to accept',
	INVALID_FRIEND_ID: 'Invalid friend ID',
	FRIEND_REQUEST_ACCEPTED: 'Friend request accepted successfully',
	FRIEND_REQUEST_REJECTED: 'Friend request rejected successfully',
};