const socketEvents = {

  CREATE_USER_SOCKET: 'CREATE_USER_SOCKET',
  LOGOUT_USER: 'LOGOUT_USER',
  JOIN_PRIVATE_ROOM: 'JOIN_PRIVATE_ROOM',
  RECEIVE_MESSAGES: 'RECEIVE_MESSAGES',
  SEND_MESSAGE: 'SEND_MESSAGE',
  RECEIVE_NEW_MESSAGE: 'RECEIVE_NEW_MESSAGE',
  ONLINE_STATUS: 'ONLINE_STATUS',
  PRIVATE_MESSAGES_COUNT: 'PRIVATE_MESSAGES_COUNT',
  DELETE_PRIVATE_MESSAGE: 'DELETE_PRIVATE_MESSAGE',
  TYPING_STATUS: 'TYPING_STATUS',
  DISCONNECT: 'disconnect',
  NEW_NOTIFICATION: 'NEW_NOTIFICATION',
  SET_RECEIVER_DETAILS: 'SET_RECEIVER_DETAILS',
  
  JOIN_GROUP_ROOM: 'JOIN_GROUP_ROOM',
  GROUP_MESSAGES_COUNT: 'GROUP_MESSAGES_COUNT',
  SOCKET_USER_DATA: 'SOCKET_USER_DATA',
  USER_TYPING_STATUS: 'USER_TYPING_STATUS',
  ADD_GROUP_TO_GROUPLIST: 'ADD_GROUP_TO_GROUPLIST',
  UPDATE_DELETED_PRIVATE_MESSAGE: 'UPDATE_DELETED_PRIVATE_MESSAGE',
};

export default socketEvents;